In [ ]:
#classification

In [ ]:
import pandas as pd

In [ ]:
data = {
    "Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Pass": [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

   Hours_Studied  Pass
0              1     0
1              2     0
2              3     0
3              4     0
4              5     0
5              6     1
6              7     1
7              8     1
8              9     1
9             10     1

In [ ]:
#seperate input and output

In [ ]:
X = df[["Hours_Studied"]]
Y = df["Pass"]

In [ ]:
X

   Hours_Studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

In [ ]:
Y

0    0
1    0
2    0
3    0
4    0
5    1
6    1
7    1
8    1
9    1
Name: Pass, dtype: int64

In [ ]:
#Split data into training and testing

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
X_train

   Hours_Studied
5              6
0              1
7              8
2              3
9             10
4              5
3              4
6              7

In [ ]:
X_test

   Hours_Studied
8              9
1              2

In [ ]:
Y_train

5    1
0    0
7    1
2    0
9    1
4    0
3    0
6    1
Name: Pass, dtype: int64

In [ ]:
Y_test

8    1
1    0
Name: Pass, dtype: int64

In [ ]:
# Import Logistics Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
#create and train model

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
#prediction

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([1, 0])

In [ ]:
Y_test

8    1
1    0
Name: Pass, dtype: int64

In [ ]:
prediction = model.predict([[7.5]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
prediction

array([1])

In [ ]:
prediction = model.predict([[7.5]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
prediction

array([1])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(Y_test, y_pred)

In [ ]:
accuracy

1.0

In [ ]:
Y_prob =  model.predict_proba(X_test)

In [ ]:
Y_prob

array([[0.01799637, 0.98200363],
       [0.98200563, 0.01799437]])