In [ ]:
# movies.csv

In [ ]:
# load the data and plot the scatter chart to check the patterns

In [ ]:
import pandas as pd
import seaborn as sns

In [5]:
from google.colab import files
uploaded = files.upload()

Saving movies.csv.csv to movies.csv.csv

In [7]:
df = pd.read_csv('movies.csv.csv')

In [8]:
df.head(3)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [15]:
print(df.columns)

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [16]:
df.columns.tolist()

['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased']

In [18]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [25]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0