In [1]:
# Social_Network_Ads.csv

In [2]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv

In [5]:
df = pd.read_csv('Social_Network_Ads.csv')
df
# for windows with whole path
# df = pd.read_csv(r'/home/aditya/Interns_2026/daily_codes/week6/Social_Network_Ads.csv')c

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
df.shape

(400, 5)

In [7]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [8]:
newdf = df.copy()

In [9]:
newdf

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [10]:
# import the label encoder class
from sklearn.preprocessing import LabelEncoder

In [11]:
le = LabelEncoder() # creating the class

In [12]:
newdf['Gender'] = le.fit_transform(newdf['Gender'])

In [13]:
newdf

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [14]:
le.classes_

array(['Female', 'Male'], dtype=object)

In [15]:
#  one hot encoding

In [16]:
df = pd.get_dummies(df)

In [17]:
df

      User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510   19            19000          0          False         True
1    15810944   35            20000          0          False         True
2    15668575   26            43000          0           True        False
3    15603246   27            57000          0           True        False
4    15804002   19            76000          0          False         True
..        ...  ...              ...        ...            ...          ...
395  15691863   46            41000          1           True        False
396  15706071   51            23000          1          False         True
397  15654296   50            20000          1           True        False
398  15755018   36            33000          0          False         True
399  15594041   49            36000          1           True        False

[400 rows x 6 columns]

In [18]:
import seaborn as sns

In [19]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [20]:
import seaborn as sns
df = sns.load_dataset('taxis');
df;

In [21]:
"""
load the taxis dataset from seaborn
remove pickup and dropoff columns from the dataset
encode all the categorical columns using Label Encoding
ideally create a function which encode when u pass the dataframe
""";

In [22]:
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = sns.load_dataset("taxis")

df = df.drop(columns=["pickup", "dropoff"])

def label_encode_dataframe(dataframe):
    le = LabelEncoder()
    df = dataframe.copy()

    for col in df.select_dtypes(include=["object", "category"]).columns:
        df[col] = le.fit_transform(df[col].astype(str))

    return df

encoded_df = label_encode_dataframe(df)

print(encoded_df.head())

   passengers  distance  fare   tip  tolls  total  color  payment  \
0           1      1.60   7.0  2.15    0.0  12.95      1        1
1           1      0.79   5.0  0.00    0.0   9.30      1        0
2           1      1.37   7.5  2.36    0.0  14.16      1        1
3           1      7.70  27.0  6.15    0.0  36.95      1        1
4           3      2.16   9.0  1.10    0.0  13.40      1        1

   pickup_zone  dropoff_zone  pickup_borough  dropoff_borough
0           99           176               2                2
1          174           182               2                2
2            1           190               2                2
3           86           202               2                2
4          116           202               2                2

In [23]:
import seaborn as sns
import pandas as pd

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
df = sns.load_dataset("taxis")

In [26]:
df = df.drop(columns=["pickup", "dropoff"])

In [27]:
def label_encode_dataframe(dataframe):
    le = LabelEncoder()
    df = dataframe.copy()

In [28]:
for col in df.select_dtypes(include=["object", "category"]).columns:
        df[col] = le.fit_transform(df[col].astype(str))

In [31]:
print(encoded_df.head())

   passengers  distance  fare   tip  tolls  total  color  payment  \
0           1      1.60   7.0  2.15    0.0  12.95      1        1
1           1      0.79   5.0  0.00    0.0   9.30      1        0
2           1      1.37   7.5  2.36    0.0  14.16      1        1
3           1      7.70  27.0  6.15    0.0  36.95      1        1
4           3      2.16   9.0  1.10    0.0  13.40      1        1

   pickup_zone  dropoff_zone  pickup_borough  dropoff_borough
0           99           176               2                2
1          174           182               2                2
2            1           190               2                2
3           86           202               2                2
4          116           202               2                2